require("dotenv").config();
const express=require("express"),http=require("http"),path=require("path"),WebSocket=require("ws");
const app=express(),server=http.createServer(app),wss=new WebSocket.Server({server}),PORT=process.env.PORT||10000,PUBLIC_DIR=path.join(__dirname,"public");
const LANES=[180,450,720];
const HEROES={warrior:{name:"Warrior",maxHp:130,damage:16,range:150,speed:1,q:34,w:42,e:28,r:85},mage:{name:"Mage",maxHp:90,damage:10,range:180,speed:1,q:46,w:28,e:20,r:110},assassin:{name:"Assassin",maxHp:80,damage:22,range:140,speed:1.18,q:58,w:20,e:38,r:125}};
const ITEMS={blade:{name:"Клинок",cost:250,damage:6,max:3},armor:{name:"Броня",cost:250,hp:35,max:3},boots:{name:"Сапоги",cost:300,speed:.22,max:2}};
const rooms=new Map();
app.disable("x-powered-by");app.use(express.json({limit:"256kb"}));app.use(express.static(PUBLIC_DIR));app.get("/health",(_,res)=>res.json({ok:true,game:"Pixel Clash",version:"2.5.0"}));app.get("/",(_,res)=>res.sendFile(path.join(PUBLIC_DIR,"index.html")));
wss.on("connection",ws=>{ws.roomId=null;ws.player=null;ws.isAlive=true;ws.lastAttack=0;ws.cooldowns={};ws.on("pong",()=>ws.isAlive=true);
ws.on("message",raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return};
if(m.type==="join"){const mode=m.mode==="5v5"?"5v5":"3v3",max=mode==="5v5"?10:6;let room=[...rooms.values()].find(r=>r.mode===mode&&!r.finished&&r.players.length<r.maxPlayers);if(!room){const id=Math.random().toString(36).slice(2,9);room={id,mode,maxPlayers:max,players:[],minions:[],towers:createTowers(),bases:createBases(),nextMinion:Date.now()+1500,startedAt:Date.now(),finished:false,winner:null}}if(!rooms.has(room.id))rooms.set(room.id,room);const i=room.players.length,team=i<max/2?1:2,key=HEROES[m.hero]?m.hero:"warrior",h=HEROES[key],p={id:Math.random().toString(36).slice(2,9),name:String(m.name||"Player").slice(0,18),hero:key,heroName:h.name,team,x:team===1?115:885,y:LANES[i%3],hp:h.maxHp,maxHp:h.maxHp,alive:true,respawnAt:0,gold:500,kills:0,deaths:0,damageBonus:0,speedBonus:0,inventory:[],level:1,xp:0,skillPoints:0,skillLevels:{q:1,w:1,e:1,r:1}};room.players.push(p);ws.roomId=room.id;ws.player=p;return broadcastState(room)}
if(!ws.roomId||!ws.player)return;const room=rooms.get(ws.roomId);if(!room||room.finished)return;const p=ws.player;
if(m.type==="move"&&p.alive){const tx=Number(m.x),ty=Number(m.y),step=60*(stat(p,"speed")+(p.speedBonus||0));if(Number.isFinite(tx))p.x=clamp(p.x+clamp(tx-p.x,-step,step),80,920);if(Number.isFinite(ty))p.y=clamp(p.y+clamp(ty-p.y,-step,step),80,820);return broadcastState(room)}
if(m.type==="attack"&&p.alive){if(Date.now()-ws.lastAttack<450)return;ws.lastAttack=Date.now();damageNearest(room,p,stat(p,"range"),stat(p,"damage")+p.damageBonus);broadcast(room,{type:"combat",action:"attack",by:p.id});return broadcastState(room)}
if((m.type==="skill"||m.type==="ability")&&p.alive)return ability(room,ws,String(m.key||"q").toLowerCase());
if(m.type==="buy"&&p.alive){const key=String(m.item||""),it=ITEMS[key],owned=p.inventory.filter(x=>x===key).length;if(!it||owned>=it.max)return;const cost=it.cost*(owned+1);if(p.gold<cost)return;p.gold-=cost;p.inventory.push(key);if(it.damage)p.damageBonus+=it.damage;if(it.hp){p.maxHp+=it.hp;p.hp+=it.hp}if(it.speed)p.speedBonus+=it.speed;broadcast(room,{type:"purchase",item:it.name,level:owned+1,cost,by:p.id});broadcastState(room)}});
ws.on("close",()=>{const room=rooms.get(ws.roomId);if(!room)return;room.players=room.players.filter(x=>x.id!==ws.player?.id);if(!room.players.length)rooms.delete(room.id);else broadcastState(room)})});
function ability(room,ws,key){if(!["q","w","e","r"].includes(key))return;const cd={q:3500,w:6000,e:8000,r:20000},now=Date.now();if(now-(ws.cooldowns[key]||0)<cd[key])return;ws.cooldowns[key]=now;const p=ws.player,rank=p.skillLevels[key]||1;let hits=0;
if(key==="q"){const range=p.hero==="mage"?280:p.hero==="assassin"?190:170,dmg=stat(p,"q")+p.damageBonus+rank*3;for(const t of room.players)if(t.team!==p.team&&t.alive&&dist(p,t)<=range){applyDamage(room,t,dmg,p);hits++}for(const t of room.minions)if(t.team!==p.team&&t.hp>0&&dist(p,t)<=range){applyDamage(room,t,dmg,p);hits++}for(const t of room.towers)if(t.alive&&t.team!==p.team&&dist(p,{x:t.x,y:t.laneY})<=range){damageTower(room,t,dmg,p);hits++}}
else if(key==="w"){const heal=stat(p,"w")+Math.round(p.maxHp*(p.hero==="warrior"?.18:.12))+rank*4;p.hp=Math.min(p.maxHp,p.hp+heal)}
else if(key==="e"){const dir=p.team===1?1:-1;p.x=clamp(p.x+dir*(p.hero==="assassin"?150:100),80,920);const dmg=stat(p,"e")+p.damageBonus+rank*2;for(const t of room.players)if(t.team!==p.team&&t.alive&&dist(p,t)<=90){applyDamage(room,t,dmg,p);hits++}}
else {const range=240,dmg=stat(p,"r")+p.damageBonus+rank*5;for(const t of room.players)if(t.team!==p.team&&t.alive&&dist(p,t)<=range){applyDamage(room,t,dmg,p);hits++}for(const t of room.minions)if(t.team!==p.team&&t.hp>0&&dist(p,t)<=range){applyDamage(room,t,dmg,p);hits++}for(const t of room.towers)if(t.alive&&t.team!==p.team&&dist(p,{x:t.x,y:t.laneY})<=range){damageTower(room,t,dmg,p);hits++}}
broadcast(room,{type:"ability",key,hero:p.hero,by:p.id,hits,cd:cd[key],rank});broadcast(room,{type:"effect",key,x:p.x,y:p.y,team:p.team});checkVictory(room);broadcastState(room)}
function createTowers(){const a=[];for(const team of [1,2])for(const y of LANES){a.push({id:`t-${team}-${y}-1`,team,laneY:y,x:team===1?245:755,hp:180,maxHp:180,tier:1,alive:true,lastShot:0});a.push({id:`t-${team}-${y}-2`,team,laneY:y,x:team===1?390:610,hp:220,maxHp:220,tier:2,alive:true,lastShot:0})}return a}
function createBases(){return[{id:"base-1",team:1,x:90,y:450,hp:600,maxHp:600},{id:"base-2",team:2,x:910,y:450,hp:600,maxHp:600}]}
function stat(p,k){return HEROES[p.hero]?.[k]??HEROES.warrior[k]}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function damageTower(r,t,d,a){t.hp=Math.max(0,t.hp-d);if(t.hp===0)rewardTower(r,t,a)}
function damageNearest(r,a,range,d){let target=null,best=Infinity;for(const p of r.players)if(p.alive&&p.team!==a.team&&dist(a,p)<=range&&dist(a,p)<best){target=p;best=dist(a,p)}if(!target)for(const m of r.minions)if(m.hp>0&&m.team!==a.team&&dist(a,m)<=range&&dist(a,m)<best){target=m;best=dist(a,m)}if(!target)for(const t of r.towers)if(t.alive&&t.team!==a.team&&dist(a,{x:t.x,y:t.laneY})<=range&&dist(a,{x:t.x,y:t.laneY})<best){target=t;best=dist(a,{x:t.x,y:t.laneY})}if(!target)return;if(target.id?.startsWith("m-"))applyDamage(r,target,d,a);else if(target.id?.startsWith("t-"))damageTower(r,target,d,a);else applyDamage(r,target,d,a);checkVictory(r)}
function gainXp(p,n){if(!p||p.level>=10)return;p.xp+=n;while(p.level<10&&p.xp>=p.level*100){p.xp-=p.level*100;p.level++;p.skillPoints++;p.maxHp+=12;p.hp=Math.min(p.maxHp,p.hp+12);p.damageBonus+=2}if(p.level>=10)p.xp=0}
function applyDamage(r,t,d,a){t.hp=Math.max(0,t.hp-d);if(t.hp>0||t.alive===false)return;if(t.id?.startsWith("m-")){t.hp=0;if(a?.gold!=null){a.gold+=15;gainXp(a,25)}return}t.alive=false;t.deaths=(t.deaths||0)+1;if(a?.id&&a.id!==t.id){a.kills=(a.kills||0)+1;a.gold=(a.gold||0)+100;gainXp(a,100)}t.respawnAt=Date.now()+5000}
function rewardTower(r,t,a){if(!t.alive)return;t.alive=false;t.hp=0;for(const p of r.players)if(p.team===a.team){p.gold+=75;gainXp(p,50)}}
function spawnMinions(r){for(const team of [1,2])for(let i=0;i<3;i++){const y=LANES[i];r.minions.push({id:`m-${Math.random().toString(36).slice(2,8)}`,team,laneY:y,x:team===1?125:875,y,hp:45,maxHp:45,speed:18,lastAttack:0})}}
function nearestHero(r,s,range){let target=null,best=Infinity;for(const p of r.players)if(p.alive&&p.team!==s.team&&dist(s,p)<=range&&Math.abs(p.y-s.y)<48&&dist(s,p)<best){target=p;best=dist(s,p)}return target}
function tickRoom(r){const now=Date.now();if(now>=r.nextMinion&&r.players.length){spawnMinions(r);r.nextMinion=now+6500}for(const p of r.players)if(!p.alive&&p.respawnAt&&now>=p.respawnAt){p.alive=true;p.hp=p.maxHp;p.x=p.team===1?115:885;p.y=LANES[Math.floor(Math.random()*3)];p.respawnAt=0}
for(const m of r.minions){if(m.hp<=0)continue;const dir=m.team===1?1:-1,h=nearestHero(r,m,42),em=r.minions.find(e=>e.hp>0&&e.team!==m.team&&e.laneY===m.laneY&&Math.abs(e.x-m.x)<34);if(h||em){if(now-m.lastAttack>=900){m.lastAttack=now;if(h)applyDamage(r,h,4,m);else applyDamage(r,em,6,m)}}else{m.x+=dir*m.speed/10;const tower=r.towers.find(t=>t.alive&&t.team!==m.team&&t.laneY===m.laneY&&Math.abs(t.x-m.x)<20);if(tower&&now-m.lastAttack>=900){m.lastAttack=now;damageTower(r,tower,5,m)}const base=r.bases.find(b=>b.team!==m.team&&Math.abs(b.x-m.x)<28&&Math.abs(b.y-m.y)<60);if(base)base.hp=Math.max(0,base.hp-2)}}
for(const t of r.towers)if(t.alive&&now-t.lastShot>=1100){const target=nearestHero(r,{team:t.team,x:t.x,y:t.laneY},155);if(target){t.lastShot=now;applyDamage(r,target,10,t)}}r.minions=r.minions.filter(m=>m.hp>0&&m.x>55&&m.x<945);checkVictory(r)}
function checkVictory(r){if(r.finished)return;const dead=r.bases.find(b=>b.hp<=0);if(!dead)return;r.finished=true;r.winner=dead.team===1?2:1;const duration=Math.round((Date.now()-r.startedAt)/1000);broadcast(r,{type:"victory",winner:r.winner,duration,stats:r.players.map(p=>({name:p.name,hero:p.heroName,team:p.team,level:p.level,xp:p.xp,gold:p.gold,kills:p.kills,deaths:p.deaths,inventory:p.inventory.slice()}))})}
function broadcastState(r){broadcast(r,{type:"state",mode:r.mode,players:r.players,minions:r.minions,towers:r.towers,bases:r.bases,lanes:LANES,finished:r.finished,winner:r.winner})}function broadcast(r,d){const s=JSON.stringify(d);wss.clients.forEach(c=>{if(c.readyState===WebSocket.OPEN&&c.roomId===r.id)c.send(s)})}
const tick=setInterval(()=>{for(const r of rooms.values())if(!r.finished){tickRoom(r);broadcastState(r)}},100);const heartbeat=setInterval(()=>wss.clients.forEach(ws=>{if(ws.isAlive===false)return ws.terminate();ws.isAlive=false;ws.ping()}),30000);wss.on("close",()=>{clearInterval(heartbeat);clearInterval(tick)});app.use((_req,res)=>res.status(404).send("Not Found"));server.listen(PORT,"0.0.0.0",()=>console.log(`Pixel Clash server listening on ${PORT}`));