require("dotenv").config();
const express=require("express"),http=require("http"),path=require("path"),WebSocket=require("ws"),{ensureBots,tickBots}=require("./bots");
const app=express(),server=http.createServer(app),wss=new WebSocket.Server({server}),PORT=process.env.PORT||10000,PUBLIC_DIR=path.join(__dirname,"public");
process.on("uncaughtException",err=>console.error("[PixelClash uncaughtException]",err?.stack||err));
process.on("unhandledRejection",err=>console.error("[PixelClash unhandledRejection]",err?.stack||err));
const LANES=[180,450,720];
const HEROES={warrior:{name:"Warrior",maxHp:130,damage:16,range:150,speed:1,q:34,w:42,e:28,r:85,armor:12},mage:{name:"Mage",maxHp:90,damage:10,range:180,speed:1,q:46,w:28,e:20,r:110,armor:5},assassin:{name:"Assassin",maxHp:80,damage:22,range:140,speed:1.18,q:58,w:20,e:38,r:125,armor:7},samurai:{name:"Samurai",maxHp:125,damage:19,range:155,speed:1.08,q:48,w:38,e:42,r:105,armor:10},shaman:{name:"Shaman",maxHp:105,damage:13,range:205,speed:.96,q:44,w:46,e:24,r:115,armor:6},cyborg:{name:"Cyborg",maxHp:150,damage:17,range:175,speed:.92,q:40,w:34,e:36,r:120,armor:18}};
const ITEMS={blade:{name:"Клинок",cost:250,damage:6,max:3},armor:{name:"Броня",cost:250,hp:35,armor:8,max:3},boots:{name:"Сапоги",cost:300,speed:.22,max:2},crit:{name:"Крит-ядро",cost:350,crit:.12,max:2},haste:{name:"Ускоритель",cost:350,cooldown:.12,max:2},vampire:{name:"Вампиризм",cost:400,lifesteal:.08,max:2}};
const SPECIALIZATIONS={"warrior-tank":{hero:"warrior",name:"Tank",title:"Страж",desc:"Получает на 12% меньше урона от героев."},"warrior-bruiser":{hero:"warrior",name:"Bruiser",title:"Берсерк",desc:"Наносит на 15% больше урона ниже 50% HP."},"mage-burst":{hero:"mage",name:"Burst",title:"Арканный взрыв",desc:"Способности наносят на 10% больше урона."},"mage-control":{hero:"mage",name:"Control",title:"Повелитель поля",desc:"Способности имеют +40 дальности."},"assassin-crit":{hero:"assassin",name:"Crit",title:"Теневой крит",desc:"Получает +10% критического шанса."},"assassin-execute":{hero:"assassin",name:"Execute",title:"Палач",desc:"На 25% больше урона целям ниже 35% HP."}};
const rooms=new Map();
app.disable("x-powered-by");app.use(express.json({limit:"256kb"}));app.use(express.static(PUBLIC_DIR));app.get("/health",(_,res)=>res.json({ok:true,game:"Pixel Clash",version:"3.6.1"}));app.get("/",(_,res)=>res.sendFile(path.join(PUBLIC_DIR,"index.html")));
wss.on("connection",ws=>{ws.roomId=null;ws.player=null;ws.isAlive=true;ws.lastAttack=0;ws.cooldowns={};ws.on("pong",()=>ws.isAlive=true);ws.on("message",raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return};
if(m.type==="join"){const mode=m.mode==="5v5"?"5v5":"3v3",max=mode==="5v5"?10:6;let room=[...rooms.values()].find(r=>r.mode===mode&&!r.finished&&r.players.filter(p=>!p.isBot).length<r.maxPlayers);if(!room){const id=Math.random().toString(36).slice(2,9);room={id,mode,maxPlayers:max,players:[],minions:[],towers:createTowers(),bases:createBases(),jungle:createJungle(),nextMinion:Date.now()+1500,startedAt:Date.now(),finished:false,winner:null,botSpawnAt:Date.now()+3500}}if(!rooms.has(room.id))rooms.set(room.id,room);const oldBot=room.players.find(p=>p.isBot);if(room.players.length>=max&&oldBot)room.players=room.players.filter(p=>p.id!==oldBot.id);const i=room.players.length,team=room.players.filter(p=>p.team===1).length<=room.players.filter(p=>p.team===2).length?1:2,key=HEROES[m.hero]?m.hero:"warrior",h=HEROES[key],p={id:Math.random().toString(36).slice(2,9),name:String(m.name||"Player").slice(0,18),hero:key,heroName:h.name,team,x:team===1?115:885,y:LANES[i%3],hp:h.maxHp,maxHp:h.maxHp,alive:true,respawnAt:0,gold:500,kills:0,deaths:0,damageBonus:0,speedBonus:0,inventory:[],level:1,xp:0,skillPoints:1,skillLevels:{q:1,w:1,e:1,r:1},specialization:null,isBot:false,damageDealt:0,towerDamage:0,buffs:[],buffUntil:0,armor:h.armor,critChance:0,cooldownReduction:0,lifesteal:0};room.players.push(p);ws.roomId=room.id;ws.player=p;return broadcastState(room)}
if(!ws.roomId||!ws.player)return;const room=rooms.get(ws.roomId);if(!room||room.finished)return;const p=ws.player;
if(m.type==="move"&&p.alive){const tx=Number(m.x),ty=Number(m.y),step=60*(stat(p,"speed")+(p.speedBonus||0));if(Number.isFinite(tx))p.x=clamp(p.x+clamp(tx-p.x,-step,step),80,920);if(Number.isFinite(ty))p.y=clamp(p.y+clamp(ty-p.y,-step,step),80,820);return broadcastState(room)}
if(m.type==="attack"&&p.alive){const interval=Math.max(220,450/(1+(p.attackSpeed||0)));if(Date.now()-ws.lastAttack<interval)return;ws.lastAttack=Date.now();damageNearest(room,p,stat(p,"range"),combatDamage(p,stat(p,"damage"),"basic"));return broadcastState(room)}
if((m.type==="skill"||m.type==="ability")&&p.alive)return ability(room,ws,String(m.key||"q").toLowerCase());
if(m.type==="specialize"&&p.alive){if(p.specialization||p.level<3)return;const key=String(m.key||"");const spec=SPECIALIZATIONS[key];if(!spec||spec.hero!==p.hero)return;p.specialization=key;if(key==="warrior-tank")p.armor+=6;if(key==="warrior-bruiser")p.damageBonus+=3;if(key==="mage-control")p.cooldownReduction=Math.min(.35,p.cooldownReduction+.05);broadcast(room,{type:"specialize",by:p.id,key,title:spec.title});return broadcastState(room)}
if(m.type==="upgrade"&&p.alive){const key=String(m.key||"").toLowerCase();if(!p.skillLevels[key]||p.skillPoints<1||p.skillLevels[key]>=5)return;p.skillPoints--;p.skillLevels[key]++;broadcast(room,{type:"upgrade",key,level:p.skillLevels[key],by:p.id});return broadcastState(room)}
if(m.type==="buy"&&p.alive){const key=String(m.item||""),it=ITEMS[key],owned=p.inventory.filter(x=>x===key).length;if(!it||owned>=it.max)return;const cost=it.cost*(owned+1);if(p.gold<cost)return;p.gold-=cost;p.inventory.push(key);if(it.damage)p.damageBonus+=it.damage;if(it.hp){p.maxHp+=it.hp;p.hp+=it.hp}if(it.speed)p.speedBonus+=it.speed;if(it.armor)p.armor+=it.armor;if(it.crit)p.critChance+=it.crit;if(it.cooldown)p.cooldownReduction=Math.min(.35,p.cooldownReduction+it.cooldown);if(it.lifesteal)p.lifesteal=Math.min(.4,p.lifesteal+it.lifesteal);if(key==="boots")p.attackSpeed=(p.attackSpeed||0)+.1;if(key==="crit")p.attackSpeed=(p.attackSpeed||0)+.04;broadcast(room,{type:"purchase",item:it.name,level:owned+1,cost,by:p.id,stats:{damage:p.damageBonus,armor:p.armor,crit:effectiveCrit(p),cooldown:p.cooldownReduction,lifesteal:p.lifesteal,attackSpeed:p.attackSpeed||0}});return broadcastState(room)}});ws.on("close",()=>{const room=rooms.get(ws.roomId);if(!room)return;room.players=room.players.filter(x=>x.id!==ws.player?.id);if(!room.players.some(x=>!x.isBot))rooms.delete(room.id);else broadcastState(room)})});
function ability(room,ws,key){if(!["q","w","e","r"].includes(key))return;const baseCd={q:3500,w:6000,e:8000,r:20000},cd=Math.round(baseCd[key]*(1-(ws.player.cooldownReduction||0))),now=Date.now();if(now-(ws.cooldowns[key]||0)<cd)return;ws.cooldowns[key]=now;const p=ws.player,rank=p.skillLevels[key]||1;let hits=0;
if(key==="q"){const range=abilityRange(p,p.hero==="mage"||p.hero==="shaman"?280:p.hero==="assassin"||p.hero==="samurai"?190:170),dmg=combatDamage(p,stat(p,"q")+rank*3,"ability");for(const t of room.players)if(t.team!==p.team&&t.alive&&dist(p,t)<=range){applyDamage(room,t,dmg,p);hits++}for(const t of room.minions)if(t.team!==p.team&&t.hp>0&&dist(p,t)<=range){applyDamage(room,t,dmg,p);hits++}for(const t of room.towers)if(t.alive&&t.team!==p.team&&dist(p,{x:t.x,y:t.laneY})<=range){damageTower(room,t,dmg,p);hits++}for(const j of room.jungle)if(j.alive&&dist(p,j)<=range){damageJungle(room,j,dmg,p);hits++}}
else if(key==="w"){const heal=stat(p,"w")+Math.round(p.maxHp*(p.hero==="warrior"||p.hero==="cyborg"?.18:.12))+rank*4;p.hp=Math.min(p.maxHp,p.hp+heal)}
else if(key==="e"){const dir=p.team===1?1:-1;p.x=clamp(p.x+dir*(p.hero==="assassin"||p.hero==="samurai"?150:100),80,920);const dmg=combatDamage(p,stat(p,"e")+rank*2,"ability");for(const t of room.players)if(t.team!==p.team&&t.alive&&dist(p,t)<=90){applyDamage(room,t,dmg,p);hits++}for(const j of room.jungle)if(j.alive&&dist(p,j)<=90){damageJungle(room,j,dmg,p);hits++}}
else {const range=abilityRange(p,240),dmg=combatDamage(p,(stat(p,"r")+rank*5)*1.15,"ability");for(const t of room.players)if(t.team!==p.team&&t.alive&&dist(p,t)<=range){applyDamage(room,t,dmg,p);hits++}for(const t of room.minions)if(t.team!==p.team&&t.hp>0&&dist(p,t)<=range){applyDamage(room,t,dmg,p);hits++}for(const t of room.towers)if(t.alive&&t.team!==p.team&&dist(p,{x:t.x,y:t.laneY})<=range){damageTower(room,t,dmg,p);hits++}for(const j of room.jungle)if(j.alive&&dist(p,j)<=range){damageJungle(room,j,dmg,p);hits++}}
broadcast(room,{type:"ability",key,hero:p.hero,by:p.id,hits,cd,rank,critChance:effectiveCrit(p)});broadcast(room,{type:"effect",key,x:p.x,y:p.y,team:p.team});checkVictory(room);broadcastState(room)}
function abilityRange(p,base){return base+(p.specialization==="mage-control"?40:0)}
function createTowers(){const a=[];for(const team of [1,2])for(const y of LANES){a.push({id:`t-${team}-${y}-1`,team,laneY:y,x:team===1?245:755,hp:180,maxHp:180,tier:1,alive:true,lastShot:0});a.push({id:`t-${team}-${y}-2`,team,laneY:y,x:team===1?390:610,hp:220,maxHp:220,tier:2,alive:true,lastShot:0})}return a}
function createBases(){return[{id:"base-1",team:1,x:90,y:450,hp:600,maxHp:600},{id:"base-2",team:2,x:910,y:450,hp:600,maxHp:600}]}
function createJungle(){return[{id:"j-blue",type:"blue",name:"Blue Sentinel",x:300,y:315,hp:260,maxHp:260,damage:8,alive:true,respawnAt:0,lastAttack:0,respawn:30000,buff:"blue"},{id:"j-red",type:"red",name:"Red Brute",x:700,y:585,hp:320,maxHp:320,damage:12,alive:true,respawnAt:0,lastAttack:0,respawn:30000,buff:"red"},{id:"j-boss",type:"boss",name:"Pixel Dragon",x:500,y:450,hp:650,maxHp:650,damage:18,alive:true,respawnAt:0,lastAttack:0,respawn:45000,buff:"dragon"}]}
function stat(p,k){return HEROES[p.hero]?.[k]??HEROES.warrior[k]}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function effectiveCrit(p){return Math.min(.75,(p.critChance||0)+(p.specialization==="assassin-crit"?.10:0))}
function combatDamage(p,base,type){let d=Math.max(0,base);if(type==="ability"&&p.specialization==="mage-burst")d*=1.10;if(p.specialization==="warrior-bruiser"&&p.hp/p.maxHp<.5)d*=1.15;if(effectiveCrit(p)>0&&Math.random()<effectiveCrit(p)){d*=2;p.lastCrit=Date.now()}return d*(1+(p.damageBuff||0))}
function damageTower(r,t,d,a){if(!t.alive)return;t.hp=Math.max(0,t.hp-d);if(a)a.towerDamage=(a.towerDamage||0)+Math.min(d,t.hp+d);if(t.hp===0)rewardTower(r,t,a)}
function rewardTower(r,t,a){if(!t.alive)return;t.alive=false;t.hp=0;for(const p of r.players)if(p.team===a.team){p.gold+=75;gainXp(p,50)}}
function damageJungle(r,j,d,a){if(!j.alive)return;const dealt=Math.min(j.hp,Math.max(0,d));j.hp=Math.max(0,j.hp-d);if(a)a.damageDealt=(a.damageDealt||0)+dealt;if(j.hp<=0){j.alive=false;j.respawnAt=Date.now()+j.respawn;const reward=j.type==="boss"?250:j.type==="red"?90:75;if(a){a.gold=(a.gold||0)+reward;gainXp(a,j.type==="boss"?180:60);a.buffs=a.buffs||[];const duration=j.type==="boss"?60000:30000;a.buffUntil=Date.now()+duration;if(!a.buffs.includes(j.buff))a.buffs.push(j.buff);if(j.buff==="blue")a.cooldownBuff=0.25;if(j.buff==="red")a.damageBuff=0.18;if(j.buff==="dragon")a.damageBuff=0.3;if(a.lifesteal)a.hp=Math.min(a.maxHp,a.hp+dealt*a.lifesteal)}broadcast(r,{type:"jungleKill",monster:j.name,by:a?.id||null,reward,buff:j.buff})}}
function damageNearest(r,a,range,d){let target=null,best=Infinity;for(const p of r.players)if(p.alive&&p.team!==a.team&&dist(a,p)<=range&&dist(a,p)<best){target=p;best=dist(a,p)}if(!target)for(const m of r.minions)if(m.hp>0&&m.team!==a.team&&dist(a,m)<=range&&dist(a,m)<best){target=m;best=dist(a,m)}if(!target)for(const t of r.towers)if(t.alive&&t.team!==a.team&&dist(a,{x:t.x,y:t.laneY})<=range&&dist(a,{x:t.x,y:t.laneY})<best){target=t;best=dist(a,{x:t.x,y:t.laneY})}if(target?.id?.startsWith("t-"))damageTower(r,target,d,a);else if(target?.id?.startsWith("j-"))damageJungle(r,target,d,a);else if(target)applyDamage(r,target,d,a)}
function applyDamage(r,t,d,a){if(!t||t.hp<=0)return;let final=d;if(t.armor)final*=100/(100+t.armor);t.hp=Math.max(0,t.hp-final);if(a)a.damageDealt=(a.damageDealt||0)+Math.min(d,t.hp+final);if(t.hp<=0&&t.alive!==false){if(t.isBot||!t.isBot){t.alive=false;t.deaths=(t.deaths||0)+1;t.respawnAt=Date.now()+5000;if(a){a.kills=(a.kills||0)+1;a.gold=(a.gold||0)+100;gainXp(a,100)}}}}
function gainXp(p,n){if(!p||p.level>=10)return;p.xp+=n;while(p.level<10&&p.xp>=p.level*100){p.xp-=p.level*100;p.level++;p.skillPoints++;p.maxHp+=12;p.hp=Math.min(p.maxHp,p.hp+12);p.damageBonus+=2}if(p.level>=10)p.xp=0}
function broadcast(r,msg){for(const p of r.players){const c=r._clients?.get(p.id);if(c&&c.readyState===1)c.send(JSON.stringify(msg))}}
function broadcastState(r){const payload={type:"state",mode:r.mode,startedAt:r.startedAt,players:r.players,minions:r.minions,towers:r.towers,bases:r.bases,jungle:r.jungle,finished:r.finished,winner:r.winner};broadcast(r,payload)}
setInterval(()=>{for(const r of rooms.values()){try{ensureBots(r);tickBots(r);broadcastState(r)}catch(e){console.error("[PixelClash tick]",e)}}},200);
server.listen(PORT,()=>console.log(`Pixel Clash running on ${PORT}`));